Require toolkit >=0.17 and use de-vsite branch of interchange
openff-toolkit >= 0.17 required to avoid ImportError: cannot import name
'NAGLChargesHandler' from
'openff.toolkit.typing.engines.smirnoff.parameters' error which has been
failing the CI.