Fix handling of DoubleExponentialVirtualSites (#85)
* Add allowed_vdw_parameter_handlers class method to _VsitePlugin

This partially addresses
https://github.com/openforcefield/openff-interchange/issues/1310.

* Require toolkit >=0.17 and use de-vsite branch of interchange

openff-toolkit >= 0.17 required to avoid ImportError: cannot import name
'NAGLChargesHandler' from
'openff.toolkit.typing.engines.smirnoff.parameters' error which has been
failing the CI.

* Increase tolerance so tests pass on macos

* Pip install main branch of interchange until new release

* Apply suggestions from code review

---------

Co-authored-by: Matt Thompson <matt.thompson@openforcefield.org>